apiVersion: v1
kind: Pod
metadata:
  name: my-custom-scheduler
  namespace: kube-system
spec:
  containers:
    - command:
        - kube-scheduler
        - --address=127.0.0.1
        - --kubeconfig=/etc/kubernetes/scheduler.conf
        - --leader-elect=true #if you have multi master,to get multi schedulers work togher set to false
        - --scheduler-name=my-custom-scheduler
        - --lock-object-name=my-custom-scheduler # lw master wa7ed wa 3awz tework el scheduler el gaded
    image: k8s.gcr.io/kube-scheduler-amd:v1.11.3
    name: kube-scheduler