apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008 #from 30000 to 32767
  selector:
    app: myapp
    type: frond-end